package com.prumo.player;

import android.app.*;import android.content.*;import android.content.pm.ActivityInfo;import android.graphics.Color;import android.net.Uri;import android.os.*;import android.view.*;import android.widget.*;import androidx.activity.result.ActivityResultLauncher;import androidx.activity.result.contract.ActivityResultContracts;import androidx.appcompat.app.AppCompatActivity;import androidx.media3.common.MediaItem;import androidx.media3.common.Player;import androidx.media3.exoplayer.ExoPlayer;import androidx.media3.ui.PlayerView;import java.io.*;import java.util.*;import org.json.*;

public class MainActivity extends AppCompatActivity {
 static final int BG=Color.BLACK; final ArrayList<Clip> clips=new ArrayList<>(); ExoPlayer player; PlayerView playerView; SharedPreferences prefs; ActivityResultLauncher<Intent> picker; boolean adminMode=false;
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setFlags(1024,1024);setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);immersive();prefs=getSharedPreferences("prumo",0);load();picker=registerForActivityResult(new ActivityResultContracts.StartActivityForResult(),r->{if(r.getResultCode()==RESULT_OK&&r.getData()!=null){Intent d=r.getData();if(d.getClipData()!=null)for(int i=0;i<d.getClipData().getItemCount();i++)copyUri(d.getClipData().getItemAt(i).getUri());else if(d.getData()!=null)copyUri(d.getData());showAdmin();}});showPlayer();}
 void immersive(){getWindow().getDecorView().setSystemUiVisibility(5894|View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY|View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN|View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION|View.SYSTEM_UI_FLAG_LAYOUT_STABLE);}
 void showPlayer(){adminMode=false;FrameLayout root=new FrameLayout(this);playerView=new PlayerView(this);playerView.setUseController(false);root.addView(playerView,new FrameLayout.LayoutParams(-1,-1));setContentView(root);if(player==null){player=new ExoPlayer.Builder(this).build();player.setRepeatMode(Player.REPEAT_MODE_ALL);player.setShuffleModeEnabled(false);playerView.setPlayer(player);}rebuildPlayer();immersive();}
 void rebuildPlayer(){if(player==null)return;ArrayList<MediaItem> items=new ArrayList<>();for(Clip c:clips)if(c.enabled)items.add(MediaItem.fromUri(Uri.fromFile(new File(c.path))));player.setMediaItems(items,true);if(!items.isEmpty()){player.prepare();player.play();}}
 void showAdmin(){adminMode=true;if(player!=null)player.pause();LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(32,28,32,28);root.setBackgroundColor(Color.rgb(16,16,16));root.addView(txt("PRUMO  •  CONFIGURAÇÃO",24,Color.WHITE),new LinearLayout.LayoutParams(-1,70));Button add=btn("IMPORTAR VÍDEOS (USB / ARMAZENAMENTO)");add.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("video/*");i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);i.addCategory(Intent.CATEGORY_OPENABLE);picker.launch(i);});root.addView(add);root.addView(txt("PIN atual: "+prefs.getString("pin","1234")+"   •   MENU/BACK retorna",14,Color.LTGRAY),new LinearLayout.LayoutParams(-1,50));ScrollView sv=new ScrollView(this);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);for(int i=0;i<clips.size();i++){final int idx=i;LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(0,8,0,8);row.addView(txt((i+1)+". "+clips.get(i).name,16,Color.WHITE),new LinearLayout.LayoutParams(0,70,1));Button tog=btn(clips.get(i).enabled?"ATIVO":"PAUSADO");tog.setOnClickListener(v->{clips.get(idx).enabled=!clips.get(idx).enabled;save();showAdmin();});row.addView(tog,new LinearLayout.LayoutParams(150,65));Button up=btn("↑");up.setOnClickListener(v->{if(idx>0){Collections.swap(clips,idx,idx-1);save();showAdmin();}});row.addView(up,new LinearLayout.LayoutParams(80,65));Button dn=btn("↓");dn.setOnClickListener(v->{if(idx<clips.size()-1){Collections.swap(clips,idx,idx+1);save();showAdmin();}});row.addView(dn,new LinearLayout.LayoutParams(80,65));Button del=btn("X");del.setOnClickListener(v->{try{new File(clips.get(idx).path).delete();}catch(Exception ignored){}clips.remove(idx);save();showAdmin();});row.addView(del,new LinearLayout.LayoutParams(80,65));list.addView(row);}sv.addView(list);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));Button play=btn("SALVAR E INICIAR REPRODUÇÃO");play.setOnClickListener(v->showPlayer());root.addView(play,new LinearLayout.LayoutParams(-1,75));setContentView(root);immersive();root.requestFocus();}
 TextView txt(String s,int size,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setGravity(Gravity.CENTER_VERTICAL);return t;}Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextSize(14);b.setTextColor(Color.WHITE);b.setAllCaps(false);return b;}
 void requestAdmin(){final EditText e=new EditText(this);e.setInputType(2);e.setHint("PIN");e.setTextColor(Color.WHITE);e.setSingleLine(true);new AlertDialog.Builder(this).setTitle("PRUMO").setMessage("Acesso à configuração").setView(e).setNegativeButton("Cancelar",null).setPositiveButton("Entrar",(d,w)->{if(e.getText().toString().equals(prefs.getString("pin","1234")))showAdmin();else Toast.makeText(this,"PIN incorreto",Toast.LENGTH_SHORT).show();}).show();}
 void copyUri(Uri u){try{String name="video_"+System.currentTimeMillis()+".mp4";String q=u.getLastPathSegment();if(q!=null&&q.contains("/"))q=q.substring(q.lastIndexOf('/')+1);if(q!=null&&!q.isEmpty())name=q;File dir=new File(getExternalFilesDir(null),"videos");dir.mkdirs();File out=new File(dir,name);InputStream in=getContentResolver().openInputStream(u);FileOutputStream fos=new FileOutputStream(out);byte[] buf=new byte[1048576];int n;while((n=in.read(buf))>0)fos.write(buf,0,n);in.close();fos.close();clips.add(new Clip(name,out.getAbsolutePath(),true));save();}catch(Exception e){Toast.makeText(this,"Falha ao importar: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
 void save(){JSONArray a=new JSONArray();try{for(Clip c:clips){JSONObject o=new JSONObject();o.put("name",c.name);o.put("path",c.path);o.put("enabled",c.enabled);a.put(o);}}catch(Exception ignored){}prefs.edit().putString("clips",a.toString()).apply();}
 void load(){clips.clear();try{JSONArray a=new JSONArray(prefs.getString("clips","[]"));for(int i=0;i<a.length();i++){JSONObject o=a.getJSONObject(i);String p=o.getString("path");if(new File(p).exists())clips.add(new Clip(o.getString("name"),p,o.optBoolean("enabled",true)));}}catch(Exception ignored){}}
 @Override public boolean onKeyDown(int key,KeyEvent e){if(key==KeyEvent.KEYCODE_MENU||key==KeyEvent.KEYCODE_SETTINGS||key==KeyEvent.KEYCODE_GUIDE){if(!adminMode)requestAdmin();else showPlayer();return true;}if(key==KeyEvent.KEYCODE_BACK&&adminMode){showPlayer();return true;}return super.onKeyDown(key,e);}
 @Override protected void onDestroy(){if(player!=null){player.release();player=null;}super.onDestroy();}
 static class Clip{String name,path;boolean enabled;Clip(String n,String p,boolean e){name=n;path=p;enabled=e;}}
}
